### ISSUE TITLE
SQL exception when parsing TRF

### ISSUE THREAD

**Issue by cpoenisch** [jenkinsci/ecutest-plugin#41]
SQL parsing exception occured when uploading ATX report to TEST-GUIDE in Windows Docker environment.

Console log:
```
[TT] INFO: - Generating and uploading ATX reports...
[TT] INFO: -> Generating and uploading ATX report: C:\Workspaces\TestWorkspace\TestReports\Package_xxx\Package.trf
ERROR: Step ‘[TT] Publish ATX Reports’ aborted due to exception: 
java.sql.SQLException: ResultSet closed
	at org.sqlite.RS.checkOpen(RS.java:63)
	at org.sqlite.RS.findColumn(RS.java:108)
	at org.sqlite.RS.getString(RS.java:317)
	at de.tracetronic.jenkins.plugins.ecutest.report.atx.ATXReportUploader$ParseTRFCallable.call(ATXReportUploader.java:580)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip/ip:49175
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at de.tracetronic.jenkins.plugins.ecutest.report.atx.ATXReportUploader.upload(ATXReportUploader.java:120)
		at de.tracetronic.jenkins.plugins.ecutest.report.atx.ATXPublisher.publishReports(ATXPublisher.java:158)
		at de.tracetronic.jenkins.plugins.ecutest.report.atx.ATXPublisher.performReport(ATXPublisher.java:119)
		at de.tracetronic.jenkins.plugins.ecutest.report.AbstractReportPublisher.perform(AbstractReportPublisher.java:262)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1841)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused: java.io.IOException
	at de.tracetronic.jenkins.plugins.ecutest.report.atx.ATXReportUploader$ParseTRFCallable.call(ATXReportUploader.java:589)
	at de.tracetronic.jenkins.plugins.ecutest.report.atx.ATXReportUploader$ParseTRFCallable.call(ATXReportUploader.java:553)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by cpoenisch** [comment]
As generated TRF was invalid (empty content) throwing exception is acceptable.
