### ISSUE TITLE
"testProject" with "recordWarnings: true" leads to failure

### ISSUE THREAD

**Issue by PP-DanielB** [jenkinsci/ecutest-plugin#618]
**Describe the bug**
ECU-Test project cannot be started with Jenkins pipeline step "testProject" if "recordWarnings" set to true. Leads to console output:
```
java.lang.NoClassDefFoundError: io/jenkins/plugins/analysis/core/util/StageResultHandler
	at de.tracetronic.jenkins.plugins.ecutest.extension.warnings.WarningsRecorder.record(WarningsRecorder.java:88)
	at de.tracetronic.jenkins.plugins.ecutest.test.client.AbstractTestClient.recordWarnings(AbstractTestClient.java:160)
	at de.tracetronic.jenkins.plugins.ecutest.test.client.ProjectClient.runTestCase(ProjectClient.java:81)
	at de.tracetronic.jenkins.plugins.ecutest.test.TestProjectBuilder.runTest(TestProjectBuilder.java:71)
	at de.tracetronic.jenkins.plugins.ecutest.test.AbstractTestBuilder.performTest(AbstractTestBuilder.java:200)
	at de.tracetronic.jenkins.plugins.ecutest.test.AbstractTestBuilder.perform(AbstractTestBuilder.java:88)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

**To Reproduce**
- Create an empty ECU - Test project within a Jenkins agent workspace folder
- No ECU - Test test configuration loaded
- No ECU - Test test bench configuration loaded
- Run Jenkins pipeline with the following steps:
```
    startET (
        toolName: 'ECU-Test',
        workspaceDir: (
            "C:\\Jenkins\\workspace\\..."
        )
    )
    testProject(
        executionConfig: [checkTestFile: true, recordWarnings: true, stopOnError: true, timeout: '60'],
        testConfig: [
            keepConfig: true,
            loadOnly: false
        ],
        testFile: 'C:\\Jenkins\\workspace\\...\\Testprojekt.prj'
    )
```

**Expected behavior**
Project should be executed also with recordWarnings set to true.

**Versions**
- Jenkins: 2.425
- ECU-TEST Plugin: 2.42
- Warnings Plugin: 10.5.0
- ECU-TEST: 2021.2

**Comment by ErikRehmTT** [comment]
Hi, the described issue will be fixed with the next release. While reproducing you issue we discovered some more issues with the warnings-ng integration, which will be solved with #714 
Thank you for reporting the bug and sorry for the late reply in this issue
